### ISSUE TITLE
Failed to get the task id.

### ISSUE THREAD

**Issue by dawoodjee** [Myddleware/myddleware#234]
Trying to run a sync between a MSSQL View and an ERPNext Module
- v2.5.0d
- SQL 2017
- ERPNext 11

The connections are working fine, successfully created the rules but getting this message when I try to run it:
![image](https://user-images.githubusercontent.com/7912989/69284388-33ac9f00-0bf7-11ea-986c-f53d13005cd1.png)

Heres my rule setup:

I cant figure out what I'm missing, or is it a bug?
The task runs fine in rule simulation after saving it.

3. 
![image](https://user-images.githubusercontent.com/7912989/69284454-5343c780-0bf7-11ea-8750-c411e08fca1d.png)

4. 

![image](https://user-images.githubusercontent.com/7912989/69284493-6eaed280-0bf7-11ea-9acb-f93c164c84ee.png)

5. 

![image](https://user-images.githubusercontent.com/7912989/69284551-8dad6480-0bf7-11ea-91d7-00611c1e00e7.png)

6. 

![image](https://user-images.githubusercontent.com/7912989/69284575-9f8f0780-0bf7-11ea-8e14-1f028e75b98a.png)

7. 

![image](https://user-images.githubusercontent.com/7912989/69284677-d6651d80-0bf7-11ea-9d6c-301c0fd0897a.png)

**Comment by Myddleware** [comment]
Hi @dawoodjee ,
Could you try to run this task from a command prompt : 
php bin/console myddleware:synchro ALL--env=background

**Comment by dawoodjee** [comment]
Hi @Myddleware 

Thanks for the response. Here's the result
```
$ C:\xampp\htdocs\myddleware> php bin/console myddleware:synchro ALL--env=background

1;5dd79804640803.38281593                                                                                                                                                                       
ALL--env=background                                                                                                                                                                             
Read data for rule : ALL--env=background                                                                                                                                                        
0;Rule ALL--env=background doesn't exist or is deleted. 

$ C:\xampp\htdocs\myddleware>
```


![image](https://user-images.githubusercontent.com/7912989/69410576-03a6ee00-0d14-11ea-9bde-8b536f5b5875.png)

**Comment by Myddleware** [comment]
OK I see, you have probably a permission issue. Please make sure you directory car/cache and var/logs is writtable. Then it should work properly.
Please, keep me posted.

**Comment by dawoodjee** [comment]
I've assigned Full Control to the Windows Apache User (my user account) but still getting the same error. 

In Ubuntu I did chown for the web-user and chmod 777 and still got this issue in the UI, I'm going to test the command line.

**Comment by dawoodjee** [comment]
Ubuntu gives the same error:

```
ubuntu:/var/www/html/myddleware$:php bin/console myddleware:synchro ALL--env=background
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php/20160303/pdo_sqlsrv' - /usr/lib/php/20160303/pdo_sqlsrv: undefined symbol: php_pdo_register_driver in Unknown on line 0
PHP Warning:  Module 'sqlsrv' already loaded in Unknown on line 0
PHP Warning:  Module 'pdo_sqlsrv' already loaded in Unknown on line 0
1;5dd7aad2ee5172.59558735
ALL--env=background
Read data for rule : ALL--env=background
0;Rule ALL--env=background doesn't exist or is deleted.
```

**Comment by Myddleware** [comment]
OK, could you tell me what is your php version (you can run the command "php -v" in your prompt) ? Thanks.

**Comment by dawoodjee** [comment]
Windows is running PHP 7.3 

Ubuntu is running PHP 7.1

I'm aware that myddleware runs on 7.1 and 7.2

**Comment by Myddleware** [comment]
OK, could you create a rule betwen ERPNext and ERPNext, just to make a small test and check if the rule is working properly.
It is just to be sure the error is because of the MSSQL connector.
Thanks.

**Comment by Myddleware** [comment]
Oh sorry, I see another thing, there is no space between "ALL" and "--env" in the command I gave you. Could you retry first (before createing the rule between ERPNext and ERPNext) this command : 
`php bin/console myddleware:synchro ALL --env=background`

Thanks.

**Comment by Myddleware** [comment]
Could you try to run a Symfony standard command like this one : 
`php bin/console cache:clear --env=prod`

Do you still have the error ? If yes, it shouldn't be linked to Myddleware but to the installation of the driver sqlsrv on your server.

**Comment by slemo** [comment]
I am seeing the same issue. I tried the steps provided above without success. Below are some screenshots showing the various errors I am seeing. Could you help?

![image](https://user-images.githubusercontent.com/9007606/81299938-a510ca80-903c-11ea-900b-c0e319198254.png)

![image](https://user-images.githubusercontent.com/9007606/81300116-ddb0a400-903c-11ea-8f90-d47e2d8c2dae.png)

**Comment by Myddleware** [comment]
Hi @slemo ,
OK let's talk about the task id issue here. If you want we address the 18 errors you get with mailchimp, could you plese open a new issue with the error detail of one of these 18 data transfers. Thanks.

About the task ID, did you try what I have said in my first answer by running this command : 
`php bin/console myddleware:synchro ALL --env=background`
Do you have an error or does it work properly ?

**Comment by slemo** [comment]
Hello there, I am impressed by how quickly you are following up on issues by the way. Thank you for that. I will create a different ticket for the 18 errors for Mailchimp transfer. 

As to the task id problem, here is the outcome when I run the command: php bin/console myddleware:synchro ALL--env=background

![image](https://user-images.githubusercontent.com/9007606/81313721-d9d94d80-904d-11ea-951a-0454b0045961.png)

**Comment by Myddleware** [comment]
Sorry I forgot a space between ALL and --env in this command (I have corrected my previous post too). Could you try this one :  
`php bin/console myddleware:synchro ALL --env=background`

**Comment by slemo** [comment]
Thank you.  Here is the screenshot of the result I get with the last command you send. 

![image](https://user-images.githubusercontent.com/9007606/81319290-12305a00-9055-11ea-83a5-ba006c80c9f3.png)

**Comment by Myddleware** [comment]
Ok so the task seems to run properly when you run it from the prompt command. If you go to the task list in Myddleware, you should be able to see the task you have just run.

So the problem is when you run the task from Myddleware. This is probably because some permissions are missing for the webuser on the directories : 
```
/myddleware/var/cache
/myddleware/var/logs
```
Could you make user that your webuser (for example www-data when you use apache) has the permission to write in these modules ?

**Comment by slemo** [comment]
I gave 777 permissions to those folders and files but I still get the task id error. It seems like I can only run from the shell command.

**Comment by Myddleware** [comment]
Hi @slemo,
Do this directory exist in your Myddleware : myddleware\var\cache\prod\myddleware\job ? 
If yes, do you have some files in this directory ? 

Could you also try to use Myddleware in dev environment ? For this please change the end of your Myddleware url by /web/app_dev.php . Do you still have the error in dev environement ? 

Thanks.

**Comment by slemo** [comment]
Thank you. The directory you asked does exist. Here is a screenshot of the folder. Also, I changed to the development environment and I got the same error "Failed to get the task id."

![image](https://user-images.githubusercontent.com/9007606/82061349-3233cf00-968e-11ea-9bd9-cb792a1265a5.png)

**Comment by Myddleware** [comment]
Thanks.
It seems that all your files are empty. You should have at least an id in it, even if the task has read no data transfer.
Your web user seems to have the permission to create the files but does it the right to write into these files ?
